<<<<<<< HEAD:.github/workflows/delete-workflows.yml
name: Delete Old Workflows

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        id: workflow
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 7
=======
name: Delete Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 15
>>>>>>> 94d8d6a47514e5129c60063580b26f4e7e801fa6:.github/workflows/delete-old-workflow-runs.yml
